# Name of the workflow
name: Selenium_testing_framework

# Trigger the workflow on push events to specified branches
on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow, change if needed
      - develop  # Add any other branches you want to trigger the workflow

# Define the jobs to be run
jobs:
  # Name of the job
  build:
    # Specify the environment for the job
    runs-on: ubuntu-latest

    # List of steps to execute in the job
    steps:
    - name: Checkout code
      # Action to check out the repository code
      uses: actions/checkout@v2

    - name: Set up Python
      # Action to set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      # Command to install project dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests
      # Command to run the test suite
      run: pytest